//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AspNetBankEntities : DbContext
    {
        public AspNetBankEntities()
            : base("name=AspNetBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlaceOfWork> PlaceOfWork { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Citizenship> Citizenship { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Disability> Disability { get; set; }
        public virtual DbSet<FamilyStatus> FamilyStatus { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Characteristic> Characteristic { get; set; }
        public virtual DbSet<ChartAccounts> ChartAccounts { get; set; }
        public virtual DbSet<Currensy> Currensy { get; set; }
        public virtual DbSet<Deposit> Deposit { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<BankDevelopmentAccount> BankDevelopmentAccount { get; set; }
    }
}
