//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDevelopmentAccount
    {
        public int Id { get; set; }
        public decimal Summ { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
    }
}
