//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public int ChartAccountsId { get; set; }
        public decimal Dedet { get; set; }
        public decimal Credit { get; set; }
        public decimal Balance { get; set; }
        public int DepositId { get; set; }
        public string Contract { get; set; }
        public int UserId { get; set; }
        public int CurrensyId { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateCreat { get; set; }
        public int InterestDeposit { get; set; }
    
        public virtual ChartAccounts ChartAccounts { get; set; }
        public virtual Currensy Currensy { get; set; }
        public virtual Deposit Deposit { get; set; }
        public virtual User User { get; set; }
    }
}
