//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNo { get; set; }
        public string PassportIssuedBy { get; set; }
        public System.DateTime DateIssuePassport { get; set; }
        public string IDNumber { get; set; }
        public string PhoneHouse { get; set; }
        public string MobilePhone { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> PlaceOfWorkID { get; set; }
        public string Position { get; set; }
        public int CityRegistrationID { get; set; }
        public string PlaceResidence { get; set; }
        public int FamilyStatusID { get; set; }
        public int CitizenshipID { get; set; }
        public int DisabilityID { get; set; }
        public bool Retiree { get; set; }
        public Nullable<double> MonthlyIncome { get; set; }
        public bool LiableMilitaryService { get; set; }
        public string PlaceBirth { get; set; }
        public int CityFactResidenceID { get; set; }
        public string ActualAddress { get; set; }
        public int SexID { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
    
        public virtual PlaceOfWork PlaceOfWork { get; set; }
        public virtual Citizenship Citizenship { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Disability Disability { get; set; }
        public virtual FamilyStatus FamilyStatus { get; set; }
        public virtual Sex Sex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
