//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNo { get; set; }
        public string PassportIssuedBy { get; set; }
        public System.DateTime DateIssuePassport { get; set; }
        public string IDNumber { get; set; }
        public string PhoneHouse { get; set; }
        public string MobilePhone { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> PlaceOfWorkID { get; set; }
    
        public virtual PlaceOfWork PlaceOfWork { get; set; }
    }
}
